seed = 42
mode = "production" # available modes: production, development
root = "/app"

[datasets]
dataset_root = "/app/datasets/target_datasets"
unlabelled_path = "/app/datasets/target_datasets"
small_labelled_path = "/app/gui/assets/labelled_datasets"

[server]
runOnSave = false
fileWatcher = "none"
headless = true
